Code/LANUG/Models/Sponsor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LANUG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Meetings = new HashSet<Meeting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string LogoURL { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime Modified { get; set; }
        public int ModifiedById { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
    }
}

Code/LANUG/Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LANUG.Models;

namespace LANUG.Controllers
{
    [Authorize]
    public class SponsorsController : Controller
    {
        private LANUGEntities db = new LANUGEntities();

        //
        // GET: /Sponsor/

        public ActionResult Index()
        {
            return View(db.Sponsors.ToList());
        }

        //
        // GET: /Sponsor/Details/5

        public ActionResult Details(int id = 0)
        {
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        //
        // GET: /Sponsor/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Sponsor/Create

        [HttpPost]
        public ActionResult Create(Sponsor sponsor)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string logoPath = "~/Media/sponsor_" + Request.Files[0].FileName;
                    if (db.Sponsors.Any(s => s.LogoURL == logoPath)) throw new ApplicationException("An image with the specified name already exists. Please rename the logo and try again.");
                    Request.Files[0].SaveAs(Server.MapPath(logoPath));
                    sponsor.LogoURL = logoPath;
                }
                sponsor.CreatedById = sponsor.ModifiedById = new UsersContext().UserProfiles.First(u => u.UserName == User.Identity.Name).UserId;
                db.Sponsors.Add(sponsor);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    string errors = string.Empty;
                    foreach (var error in db.GetValidationErrors())
                    {
                        errors += error.ValidationErrors.First().ErrorMessage + "; ";
                    }
                    throw new ApplicationException(errors);
                }
                return RedirectToAction("Index");
                //db.Sponsors.Add(sponsor);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return View(sponsor);
        }

        //
        // GET: /Sponsor/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        //
        // POST: /Sponsor/Edit/5

        [HttpPost]
        public ActionResult Edit(Sponsor sponsor)
        {
            if (ModelState.IsValid)
            {
                var oldSponsor = db.Sponsors.FirstOrDefault(s => s.Id == sponsor.Id);
                oldSponsor.Name = sponsor.Name;
                oldSponsor.Website = sponsor.Website;
                oldSponsor.Description = sponsor.Description;
                if (Request.Files.Count > 0 && !string.IsNullOrEmpty(Request.Files[0].FileName))
                {
                    string logoPath = "~/Media/sponsor_" + Request.Files[0].FileName;
                    if (logoPath.ToLower() != oldSponsor.LogoURL.ToLower())
                    {
                        // if old logo name is different then new logo name make sure the name doesn't already exist
                        if (db.Sponsors.Any(s => s.LogoURL == logoPath)) throw new ApplicationException("An image with the specified name already exists. Please rename the logo and try again.");
                        // delete old logo
                        if (!string.IsNullOrWhiteSpace(oldSponsor.LogoURL)) new FileInfo(Server.MapPath(oldSponsor.LogoURL)).Delete();
                    }
                    Request.Files[0].SaveAs(Server.MapPath(logoPath));
                    oldSponsor.LogoURL = logoPath;
                }
                oldSponsor.Modified = DateTime.Now;
                oldSponsor.ModifiedById = new UsersContext().UserProfiles.First(u => u.UserName == User.Identity.Name).UserId;
                db.Entry(oldSponsor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sponsor);
        }

        //
        // GET: /Sponsor/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Sponsor sponsor = db.Sponsors.Find(id);
            if (sponsor == null)
            {
                return HttpNotFound();
            }
            return View(sponsor);
        }

        //
        // POST: /Sponsor/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Sponsor sponsor = db.Sponsors.Find(id);
            db.Sponsors.Remove(sponsor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Code/LANUG/Views/Sponsors/Create.cshtml
@model LANUG.Models.Sponsor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sponsor</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">Logo
        </div>
        <div class="editor-field">
            <input name="fuLogo" id="fuLogo" type="file"/>
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Code/LANUG/Views/Sponsors/Delete.cshtml
@model LANUG.Models.Sponsor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Sponsor</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogoURL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogoURL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreatedById)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedById)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Modified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModifiedById)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModifiedById)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Code/LANUG/Views/Sponsors/Details.cshtml
@model LANUG.Models.Sponsor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Sponsor</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogoURL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogoURL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreatedById)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedById)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Modified)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modified)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModifiedById)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModifiedById)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Code/LANUG/Views/Sponsors/Edit.cshtml
@model LANUG.Models.Sponsor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sponsor</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        
        <div class="editor-label">Logo
        </div>
        <div class="editor-field">
            @if (!string.IsNullOrWhiteSpace(Model.LogoURL))
            {
                <img src="@Url.Content(Model.LogoURL)" height="175px" alt="@Model.Name" />
            }
            <input name="fuLogo" id="fuLogo" type="file"/>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<div class="clear"></div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Code/LANUG/Views/Sponsors/Index.cshtml
@model IEnumerable<LANUG.Models.Sponsor>

@{
    ViewBag.Title = "Index";
}

<h2>Sponsors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="list-table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>